all:
	g++ main.cpp notification/notifier.h notification/notifier.cpp notification/notificationEmail.h notification/notificationNone.h notification/SimpleEmailSender.h notification/SimpleEmailSender.cpp IConfig/IConfig.cpp IConfig/IConfig.h IConfig/iniparser.h IConfig/iniparser.cpp -o ../release/result -lcrypto -lm -std=c++11
